// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYaQDDtjFyppROt9VELTdV9WRmTv5Yg7k',
    appId: '1:506081431460:web:51faaf60fcd2c9c33c3b31',
    messagingSenderId: '506081431460',
    projectId: 'warungin-81dbb',
    authDomain: 'warungin-81dbb.firebaseapp.com',
    storageBucket: 'warungin-81dbb.firebasestorage.app',
    measurementId: 'G-YVEW8HP4ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHCjQdMoLDEY3JSqUdxW45LbilfJfOFg',
    appId: '1:506081431460:android:d944f592581237e23c3b31',
    messagingSenderId: '506081431460',
    projectId: 'warungin-81dbb',
    storageBucket: 'warungin-81dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNjR19ENHopV3X82s0cJJNwZo_ZwiHqc',
    appId: '1:506081431460:ios:0f04be7f4afc45f43c3b31',
    messagingSenderId: '506081431460',
    projectId: 'warungin-81dbb',
    storageBucket: 'warungin-81dbb.firebasestorage.app',
    iosBundleId: 'com.example.dashboardTrial',
  );

}